_commit: 1.2.5
_src_path: https://github.com/hypermedia-app/creta-template-api.git
api: api
api_delete_handler: false
collection_get_handler: true
event_handlers: false
organization: univoca
resource_get_handler: true
writable_acl: false
writable_event_handlers: false
writable_hydra_class: false

