### Get dimensions term sets
GET {{base}}/dimensions
Accept: text/turtle

### Create a dimension
POST {{base}}/dimensions
Content-Type: text/turtle

< ./body/dimensions/color.ttl

### Get created dimension
GET {{base}}/dimension/colors

### Create - missing discriminator
POST {{base}}/dimensions
Content-Type: text/turtle

< ./body/dimensions/missing-discriminator.ttl

